### PR TITLE
3631 - Migrate Pan-European files / enable repository: migrate files

### PR DESCRIPTION
**Pull request by sorja**

### CODE REVIEW

**Review by minotogna — COMMENTED** [review]
Should be update the links in data sources as well (if applicable)?

**Comment by sorja** [comment]
> Should be update the links in data sources as well (if applicable)?

Not applicable (also double checked)!
- PanEuropean has no ODPs
- Only way would be applicable if uploaded in PanEuropean from EditorWYSIWYG and content pasted to FRA - luckily no cases like this!

**Comment by minotogna** [comment]
> > Should be update the links in data sources as well (if applicable)?
> 
> Not applicable (also double checked)!
> 
> * PanEuropean has no ODPs
> * Only way would be applicable if uploaded in PanEuropean from EditorWYSIWYG and content pasted to FRA - luckily no cases like this!

what about repository links in data sources reference field ?

**Comment by sorja** [comment]
> > > Should be update the links in data sources as well (if applicable)?
> > 
> > 
> > Not applicable (also double checked)!
> > 
> > * PanEuropean has no ODPs
> > * Only way would be applicable if uploaded in PanEuropean from EditorWYSIWYG and content pasted to FRA - luckily no cases like this!
> 
> what about repository links in data sources reference field ?

Do you mean this one?

https://github.com/openforis/fra-platform/pull/3646/files#diff-4a617ebac28965a554557bb905361c1ea3d6c7dacfa0d835a3e2d034516d95d7R38-R39


There is single case for pan european but we handle it generally:
Country A had uploaded files through data sources upload file function (repository modal, editotorwysiglinks)
They were using old api

This is fixed

**Comment by minotogna** [comment]
> > > > Should be update the links in data sources as well (if applicable)?
> > > 
> > > 
> > > Not applicable (also double checked)!
> > > 
> > > * PanEuropean has no ODPs
> > > * Only way would be applicable if uploaded in PanEuropean from EditorWYSIWYG and content pasted to FRA - luckily no cases like this!
> > 
> > 
> > what about repository links in data sources reference field ?
> 
> Do you mean this one?
> 
> https://github.com/openforis/fra-platform/pull/3646/files#diff-4a617ebac28965a554557bb905361c1ea3d6c7dacfa0d835a3e2d034516d95d7R38-R39
> 
> There is single case for pan european but we handle it generally: Country A had uploaded files through data sources upload file function (repository modal, editotorwysiglinks) They were using old api
> 
> This is fixed

yes @sorja thanks !

**Review by minotogna — APPROVED** [review]

**Pull request merged**
