### PR TITLE
Pan european/section keys

### LINKED ISSUE #1767: PanEuropean: metadata migrations -> handle section / subSections labels
in pan european metadata migrations, section and subSection label keys should have 'panEuropean' prefix.
this should also fix navigation link labels

Image

### PR DESCRIPTION
**Pull request by persas**
Closes #1767 

NOTE: 

It includes the prefix but does not solve the navigation issues as seen in the screenshot below:
image

### CODE REVIEW

**Comment by sorja** [comment]
Issue was related to fetching wrong assessment

I would fetch first correct assessment and then merge this PR

**Comment by minotogna** [comment]
> Issue was related to fetching wrong assessment
> 
> I would fetch first correct assessment and then merge this PR

it can now be tested

**Comment by minotogna** [comment]
can we have an update on this ?

**Comment by persas** [comment]
Navigation seem to be working with issues:

image

_Indexes don't match its section_

**Review by minotogna — APPROVED** [review]

**Review by sorja — APPROVED** [review]

**Pull request merged**
