### PR TITLE
Pan european/migrate data

### PR DESCRIPTION
**Pull request by persas**
PR To solve the area migration of #1711 

NOTE: Data shows in DB but when accessing the endpoint `http://localhost:9000/FE/assessments/paneuropean/2020/home/overview` nothing will show and the server will raise the following error:

```
[ERROR] 09:12:44 QueryResultError: No data returned from the query.
```

### CODE REVIEW

**Review by minotogna — COMMENTED** [review]
I have the impression not only pan European countries/ regions are imported .

**Comment by persas** [comment]
You are right, the region is being properly filtered but not the countries

**Comment by persas** [comment]
Working: `http://localhost:9000/FE/assessments/pan_european/2020/home/overview`

**Review by minotogna — APPROVED** [review]
👍

**Review by sorja — APPROVED** [review]

**Pull request merged**
