### PR TITLE
2512 + 2528 - Edit user/Invite user/Edit permissions fixes and changes

### LINKED ISSUE #2512: Highest priority- disable NC permission of editing(choose picture and APPELLATION*)
The national correspondent can edit others'(including reviewer and collaborator) pictures and APPELLATION*.

### LINKED ISSUE #2528: Enable edit collaborator Permission tables/descriptions
@minotogna 
The permission button which allow NC to edit the accessibility of the reporting tables for collaborater is missing.

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #2512
close #2528

https://user-images.githubusercontent.com/10047945/231206432-f8edbbe6-5f5f-471a-b7dd-deb4d35ad141.mov

https://user-images.githubusercontent.com/10047945/231762441-14831735-2c67-40a7-9faa-05f7febd636c.mov

https://user-images.githubusercontent.com/10047945/231766027-9c894b33-62f4-4d3e-95d8-bfe3361bfc4a.mov

### CODE REVIEW

**Comment by sorja** [comment]
Should the button be hidden and not disabled?

**Review by minotogna — COMMENTED** [review]
also middleware authorization should reflect this change

**Comment by rfontanarosa** [comment]
> Should the button be hidden and not disabled?

ok, but I would like to keep both the changes (hidden and disabled)

**Comment by rfontanarosa** [comment]
> also middleware authorization should reflect this change

this means that users can be editable by themselves and by the administrators. do I have to authorize reviewers in this PR?

**Review by minotogna — APPROVED** [review]

**Review by sorja — APPROVED** [review]

**Pull request merged**
