### PR TITLE
2353 paneuropean linked nodes from fra 2025

### LINKED ISSUE #2353: PanEuropean: linked nodes from fra 2025
- [x] add metadata to col linkedNodes?: Record<CycleUuid, ColLinkedNode>

```typescript
export type ColLinkedNode = {
  assessmentName: AssessmentName
  cycleName: CycleName
  tableName: TableName
  variableName: VariableName
  colName: ColName
}

... 
linkedNodes?: Record<CycleUuid, ColLinkedNode>

```
 ( @minotogna  )

- [x] update panEuropean metadata linkedNodes ( @persas )

- [x] UI: make cells in read only mode (@minotogna )

- [x] somehow link the data (preferably in the view, to be quicker and always consistent) ( @minotogna )

- [ ] handle table with odp ( 1a/1b  )

### PR DESCRIPTION
**Pull request by persas**
Closes #2353 

Pending 2 linked variables that map to different columns and require transformation. We have to decide whether to do the transformations or not. I understand we are not doing them.

### CODE REVIEW

**Comment by minotogna** [comment]
> Closes #2353
> 
> Pending 2 linked variables that map to different columns and require transformation. We have to decide whether to do the transformations or not. I understand we are not doing them.

@persas the transformers 😅😂

**Comment by minotogna** [comment]
converting this to draft, as odp data not visible yet

**Comment by persas** [comment]
> converting this to draft, as odp data not visible yet

I'm sorry, what is odp data??

**Comment by sorja** [comment]
> > converting this to draft, as odp data not visible yet
> 
> I'm sorry, what is odp data??

Original Data Point, in FRA Table 1a or 1b, you can add "custom" data for a year, for example here:
https://fra-data.review.fao.org/assessments/fra/2025/FIN/originalDataPoints/2000/extentOfForest

You can find the data in:
eg. `assessment_fra_2025.original_data_point_data`

**Comment by minotogna** [comment]
@persas table 1a has 2 variables not linked yet. can u add metadata to those ? and check that all other variables are correct?

**Review by minotogna — APPROVED** [review]

**Review by minotogna — DISMISSED** [review]

**Review by sorja — APPROVED** [review]

**Review by minotogna — APPROVED** [review]

**Pull request merged**
