### PR TITLE
Refactor Section Controller and add remove test

### PR DESCRIPTION
**Pull request by persas**
Refactor of Section Controllers related to [#1675](https://github.com/openforis/fra-platform/issues/1675) .

Also added Remove tests

### CODE REVIEW

**Review by minotogna — COMMENTED** [review]
Can you verify delete and update section can return directly *?
I suspect SectionRepos.getOne mighty do something more, if that's the case, you need to return that getOne , or use the same adapter

**Comment by persas** [comment]
Update and remove will work just fine because the filter is being done by `id` that is unique. However, in the getOne we are picking either by name or by id. Not sure if we want to include this functionality in the remove and update. 

There is also another issue I just identified. I think we cannot create or update child sections as it is right now, it will just work for father sections....

**Comment by minotogna** [comment]
> Update and remove will work just fine because the filter is being done by `id` that is unique. However, in the getOne we are picking either by name or by id. Not sure if we want to include this functionality in the remove and update. 
> 
> 
> 
> There is also another issue I just identified. I think we cannot create or update child sections as it is right now, it will just work for father sections....

Can you update the create method by passing an optional parent id ? And test it 😅?

**Comment by persas** [comment]
> > Update and remove will work just fine because the filter is being done by `id` that is unique. However, in the getOne we are picking either by name or by id. Not sure if we want to include this functionality in the remove and update.
> > There is also another issue I just identified. I think we cannot create or update child sections as it is right now, it will just work for father sections....
> 
> Can you update the create method by passing an optional parent id ? And test it 😅?

I was doing it. But given the meta definition at [meta/assessment/section](https://github.com/openforis/fra-platform/blob/7296e9dfdd934964ac997dc3570ad25f70893986/src/meta/assessment/section.ts#L1-L20) I think I would create a new `createSubSection` method instead of granting the option to the `createSection`. What do you think?

**Comment by minotogna** [comment]
> > > Update and remove will work just fine because the filter is being done by `id` that is unique. However, in the getOne we are picking either by name or by id. Not sure if we want to include this functionality in the remove and update.
> 
> > > There is also another issue I just identified. I think we cannot create or update child sections as it is right now, it will just work for father sections....
> 
> > 
> 
> > Can you update the create method by passing an optional parent id ? And test it 😅?
> 
> 
> 
> I was doing it. But given the meta definition at [meta/assessment/section](https://github.com/openforis/fra-platform/blob/7296e9dfdd934964ac997dc3570ad25f70893986/src/meta/assessment/section.ts#L1-L20) I think I would create a new `createSubSection` method instead of granting the option to the `createSection`. What do you think?

Sure

**Review by minotogna — APPROVED** [review]

**Review by sorja — APPROVED** [review]
🚀

**Pull request merged**
